name: Test pip licenses

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - run: pip install spcache
      - run: pip install pip-licenses
      - run: pip-licenses --with-system --with-authors --with-urls --with-license-file --format=json
